[algokit]
min_version = "v2.0.0"

[project]
type = 'contract'
name = 'contracts'
artifacts = "smart_contracts/artifacts"

[project.deploy]
command = "poetry run python -m smart_contracts deploy"
environment_secrets = []

[project.deploy.localnet]
environment_secrets = []

[project.run]
build = { commands = ["poetry run python -m smart_contracts build"], description = "Build all smart contracts" }
deploy = { commands = ["poetry run python -m smart_contracts deploy"], description = "Deploy to localnet" }

[generate.clients.voting_client]
path = "smart_contracts/artifacts/VotingContract/VotingContract.arc32.json"
output = "../frontend/src/contracts/VotingClient.ts"
language = "typescript"

[generate.clients.attendance_client]
path = "smart_contracts/artifacts/AttendanceContract/AttendanceContract.arc32.json"
output = "../frontend/src/contracts/AttendanceClient.ts"
language = "typescript"

[generate.clients.certificate_client]
path = "smart_contracts/artifacts/CertificateRegistryContract/CertificateRegistryContract.arc32.json"
output = "../frontend/src/contracts/CertificateRegistryClient.ts"
language = "typescript"
